### ISSUE TITLE
[BUG] mouse hover effect on range picker

### ISSUE THREAD

**Issue by metalmaninfr** [samsam-ahmadi/react-trip-date#21]
## Expected Behavior

on range date picker, on 1st onClick on date, the mouse hover effect should stay on the day we clicked before mouseLeave

## Current Behavior

When I click on a day, a selection of days has a mouse hover effect

## Possible Solution

no idea

## Your Environment

Mac os 11.4 - Chrome 
React 17.1
next 10.3

## Additional Comments

https://gyazo.com/fc2916dd34f3dcd120ae1c9874764515

**Comment by coling** [comment]
I've seen this too. I'll try and take a look sometime soon if @samsam-ahmadi doesn't beat me to it

**Comment by coling** [comment]
Just FYI, I fixed this in a commit I've just included in an open pull request #22 
I can split this out (as it's arguably unrelated) but otherwise it should get into a release soon enough 😃

**Comment by samsam-ahmadi** [comment]
@coling @metalmaninfr, Thank you so much, Sorry I have feeling bad. I will check them ASAP.

**Comment by coling** [comment]
> @coling @metalmaninfr, Thank you so much, Sorry I have feeling bad. I will check them ASAP.

There is no rush on my part. Rest up and feel better :-)

**Comment by z-Amiryan** [comment]
I have same problem with the RangePicker component when I try to setState dates(from, to), mouse hover effect disappears.

**Comment by coling** [comment]
I think this is fixed now @samsam-ahmadi as I did fix up the class application in the recent pull request you just merged. You may want to tidy it up and make it clearer/better tho' 😄

**Comment by samsam-ahmadi** [comment]
Thanks @coling.  ​
I just merged it to test it here; I just understand we have a problem with the custom title of weeks. If you change the startOfWeek here, you can see the titles have a problem. 

http://localhost:9009/?path=/story/range-picker-component--custom-components-header-titles

**Comment by samsam-ahmadi** [comment]
I fixed it with this [commit](https://github.com/samsam-ahmadi/react-trip-date/commit/180cedccef580834e45f5eb7eb73e42f509e4e7a) 

And new release is available: @1.7.0

**Comment by coling** [comment]
> Thanks @coling. ​
> I just merged it to test it here; I just understand we have a problem with the custom title of weeks. If you change the startOfWeek here, you can see the titles have a problem.
> 
> https://killthejs.com/react-trip-date/?path=/story/range-picker-component--custom-components-header-titles

🤦🏼  I mustn't have tested that properly.... Sorry 😢  and thanks for the fix 😄

**Comment by metalmaninfr** [comment]
I'm still having the same problems, as I am resetting the `"start-date"` and the `"end_date"` to null, i think the `getEndDateForClasses` is not triggering, i think it should be called on `onClick`

https://gyazo.com/affe1abcf9dc0dfc020d0fb0abcfaf80

**Comment by samsam-ahmadi** [comment]
@metalmaninfr  Would you please reproduce it in the [codesandbox](https://codesandbox.io/) ?

**Comment by metalmaninfr** [comment]
https://codesandbox.io/s/angry-stonebraker-1wxr4

**Comment by samsam-ahmadi** [comment]
@metalmaninfr  Please check this version  react-trip-date@1.7.1

**Comment by metalmaninfr** [comment]
seems to work, thank you :)

**Comment by samsam-ahmadi** [comment]
@metalmaninfr Great. I closed this issue, if you have any other issue or ideas feel free to open issue or PR.

**Comment by z-Amiryan** [comment]
**thank you for fixing this bug))**
